### PR TITLE
Update Crossplane's Grafana provider

### PR DESCRIPTION
**Pull request by julienduchesne**
Resources were added

### CODE REVIEW

**Comment by Duologic** [comment]
> /bin/sh: 1: jsonnet: not found
:raised_eyebrow:

**Comment by julienduchesne** [comment]
> > /bin/sh: 1: jsonnet: not found
> 
> 🤨

Trying a new version of the jsonnet setup

**Comment by Duologic** [comment]
How odd.

**Review by Duologic — APPROVED** [review]

**Comment by julienduchesne** [comment]
It's because of https://github.com/google/go-jsonnet/commit/f30e2329be2c8266b473aaed5b404b6675cf5381. `go get` no longer works. Needs `go install` now

**Pull request merged**
