### PR TITLE
Add FluxCD v0.32 / v0.33 / v0.34 / v0.35

### PR DESCRIPTION
**Pull request by hamishforbes**
Do we want to deprecate / remove some of the older versions here now?

### CODE REVIEW

**Comment by Duologic** [comment]
I don't have a preference, I did an attempt once by looking for upstream supported versions, but smallish projects often do not have a definition for that. Feel free to remove some, if someone is missing any it will be easy to bring it back. Automation FTW.

**Comment by hamishforbes** [comment]
I've trimmed the versions <0.30 (which is from May), see how that goes I guess?

**Review by julienduchesne — APPROVED** [review]

**Comment by julienduchesne** [comment]
Seems like there's a jsonnet error now

**Comment by hamishforbes** [comment]
Oops 😬
Force pushed a typo fix

**Pull request merged**
