### PR TITLE
Fixes bug with CRD Kind naming

### PR DESCRIPTION
**Pull request by xvzf**
- [x] Fixes a bug when `IAMPolicy` is rendered to `IamPolicy`; this brings a renaming of the generated files. No functionality change
- [x] Fixes a bug with `safeStr` when a rendered docsonnet documentation contains `/N` which cannot be parsed by jsonnet

### CODE REVIEW

**Review by Duologic — COMMENTED** [review]
Technically this looks fine, but I don't know for sure why `CamelLower` was there in the first place.

**Comment by xvzf** [comment]
Good point. Who can give Info for this one?

**Comment by Duologic** [comment]
@sh0rez probably?

**Comment by sh0rez** [comment]
IIRC the original https://github.com/ksonnet/ksonnet-lib followed this naming scheme, thus this library inherited that for compatibility reasons. Unless I am wrong, I also fear we need to keep these for compatibility.

I still consider the naming scheme of this PR more "correct", so maybe we could generate both, but only document this one using docsonnet?

**Comment by xvzf** [comment]
We can also just assure we are using the correct kind and keep the naming scheme. I’d like to see this generator as easy and as maintainable as possible!

**Comment by xvzf** [comment]
@sh0rez @Duologic bringing this up again, wdyt would be the best approach without over-complicating the k8s generator?

**Comment by Duologic** [comment]
Maybe we can just create a reference in custom with the "wrong" directives and fix the "right" in k8s-gen so other/new libraries have it right from the first time?

**Comment by Duologic** [comment]
I just ran a few tests, this PR changes the rendering a lot, replacing `statefulSet` with `StatefulSet` and so on for all objects. I don't think that is  acceptable for compatibility reasons.

To cover the IAMPolicy thing, I suggest to resolve that on a per-library basis. wdyt?

**Comment by Duologic** [comment]
Another idea would be to have both objects `IamPolicy` and `IAMPolicy` generated by k8s-gen?

**Comment by xvzf** [comment]
I'll have time for this towards the end of the week, will have a look!

**Comment by xvzf** [comment]
Closing in favour of https://github.com/jsonnet-libs/k8s/pull/97; didn't make sense to rebase the branch as it's been way outdated

**Pull request closed without merging**
