### PR TITLE
chore(calico): update versions for 3.24

### PR DESCRIPTION
**Pull request by xaque208**

### CODE REVIEW

**Comment by xaque208** [comment]
Should we start dropping old versions?

**Comment by Duologic** [comment]
Sure, is there a support matrix we can use?

**Comment by xaque208** [comment]
Not that I'm seeing on their site, but I've asked in slack about it.

**Comment by xaque208** [comment]
I'm impatient, so add a couple drop a couple?  I removed two of the older versions.

**Review by xvzf — APPROVED** [review]
let's merge this. The old commit hash still works for users of those versions

**Pull request merged**
