### PR TITLE
feat: add crossplane 1.15

### PR DESCRIPTION
**Pull request by gopisaba**
- add crossplane 1.15
- add upbound aws 1.x versions

### CODE REVIEW

**Comment by gopisaba** [comment]
need some help please. The CI is failing on crossplane.

**Comment by mikael-lindstrom** [comment]
I think the problem is that https://doc.crds.dev/raw/github.com/upbound/provider-aws@v1.0.0 returns 502, there are a lot of CRDs for the AWS provider which causes a timeout.

**Comment by gopisaba** [comment]
> I think the problem is that https://doc.crds.dev/raw/github.com/upbound/provider-aws@v1.0.0 returns 502, there are a lot of CRDs for the AWS provider which causes a timeout.

I have replaced doc.crds.dev with the github urls. It is long list of crds but it works I think. does it makes sense to you?

**Comment by mikael-lindstrom** [comment]
Makes sense as a workaround to me, though the CRD list seems pretty hard to maintain. Not sure if there is any other way to solve it without adding new functionality, maybe the maintainers have some ideas?

**Comment by gopisaba** [comment]
> Makes sense as a workaround to me, though the CRD list seems pretty hard to maintain. Not sure if there is any other way to solve it without adding new functionality, maybe the maintainers have some ideas?

raised an [issue](https://github.com/crdsdev/doc/issues/180) on their repo 🤞🏽

**Comment by gopisaba** [comment]
@mikael-lindstrom - Is it okay to release this with this workaround and when we have answers on this [issue](https://github.com/crdsdev/doc/issues/180), we can fix it here as well?

**Comment by mikael-lindstrom** [comment]
> @mikael-lindstrom - Is it okay to release this with this workaround and when we have answers on this [issue](https://github.com/crdsdev/doc/issues/180), we can fix it here as well?

I cannot make that call since I'm not a maintainer but maybe @Duologic can assist?

**Comment by Duologic** [comment]
Running CI...

I do not see a big problem in this but Crossplane pushes the boundaries quite a bit. We might want to look at different solutions in the mid-term. Maybe a git subtree or something like that.

**Comment by xvzf** [comment]
@Duologic ping on this one - I don't see a significant blocker on getting this merged. Wdyt?

**Review by Duologic — APPROVED** [review]
Is there a way to generate that long array? This seems unmaintainable over a long period.

**Comment by gopisaba** [comment]
> I think the problem is that https://doc.crds.dev/raw/github.com/upbound/provider-aws@v1.0.0 returns 502, there are a lot of CRDs for the AWS provider which causes a timeout.

Looks like this [resolved](https://doc.crds.dev/github.com/upbound/provider-aws@v1.8.0) now but broken again after [1.9.0](https://doc.crds.dev/github.com/upbound/provider-aws@v1.9.0) :(

**Comment by Duologic** [comment]
I've made a commit that generates that list, isn't flexible enough yet to support multiple versions but it's a start.

**Pull request merged**
