### PR TITLE
Support null on builder

### PR DESCRIPTION
**Pull request by Dreamacro**
add json primitive null type

### CODE REVIEW

**Comment by xvzf** [comment]
Hey @Dreamacro thanks for the contribution! Can you provide a use-case for this? I cannot really come up with something unfortunately

**Comment by Dreamacro** [comment]
@xvzf I am currently using `https://github.com/jsonnet-libs/k8s` for codegen as the official library does not have a good jsonnet codegen library.

Currently, the `pkg/builder` package doesn't fully satisfy my usage scenario, so I've extended it with a lot of custom types (including `null`). But`null` is the basic value type of json (string number integer boolean null), and I think it's important to support it in the `pkg/builder`.

**Comment by xvzf** [comment]
I don't see a reason to not include this when it doesn't change the generated libraries here, will need to verify this first.

**Review by sh0rez — APPROVED** [review]
Given this is merely an extension to the builder (aka simple AST printer) and does not touch the generator, I cannot see a way in how this could affect our own artifacts.

LGTM

**Comment by Dreamacro** [comment]
@sh0rez @xvzf  I added a branch of null type assertions in `Marshal`

**Review by xvzf — APPROVED** [review]
lgtm & doesn't break anything :)

**Pull request merged**
